services:

  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: db_container
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ui_container
    restart: unless-stopped
    environment:
      - APP_DEBUG=false
      - DB_HOST=db
    ports:
      - "80:8000"
    depends_on:
      - db

volumes:
  db_data: