services:

  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: db_container
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    resources:
      limits:
        cpus: "0.4"
        memory: "512M"
  
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ui_container
    restart: unless-stopped
    environment:
      - DB_HOST=db
    ports:
      - "80:8000"
    depends_on:
      - db
    resources:
      limits:
        cpus: "0.4"
        memory: "512M"

volumes:
  db_data: