name: Deploy on AWS EC2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: Development

    steps:
      - name: Deploy on AWS EC2
        env:
          AWS_SSH_USERNAME: ${{ secrets.AWS_SSH_USERNAME }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        run: |
          echo "$AWS_SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_SSH_USERNAME}@${AWS_HOST} '
          # Now update source code and build new docker images
          cd ~/dynamic-app && git pull && docker-compose up --build
          '
